module

public import Dashboard.Common
public import SSG.Html
public import SSG.Tags

@[expose] public section

open Html

def footerComp (config : SConfig) : List Html :=
  let commitSha := config.custom.commitHash
  [
    .hr,
    .div [cls "footer"] [
      "Generated by commit ",
      .a s!"https://github.com/dwrensha/compfiles/commit/{commitSha}"
        [cls "external"] commitSha
    ]
  ]
